### PR TITLE
chore: Removed archived k8s reference

### PR DESCRIPTION
**Pull request by cpheps**
### Proposed Change
Removed reference to archived Kubernetes repo.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

### CODE REVIEW

**Review by jsirianni — APPROVED** [review]

**Comment by BinaryFissionGames** [comment]
This repo is also referenced in `docs/getting-started.md` and `config/google_cloud_exporter/kubernetes/README.md`.

(Side note, `docs/getting-started.md` seems outdated and like it was written for a different format, we might want to rework that one in the future)

**Comment by cpheps** [comment]
>(Side note, docs/getting-started.md seems outdated and like it was written for a different format, we might want to rework that one in the future)

Good call I'll create a ticket for new sprint to clean this up.

**Comment by cpheps** [comment]
Removed the additional references. I'm unsure if the kubernetes deployment example still makes sense with that missing.

**Comment by BinaryFissionGames** [comment]
> Removed the additional references. I'm unsure if the kubernetes deployment example still makes sense with that missing.

It seems to me like it was just a link to that repo for the example config, basically. So we should probably just remove that whole kubernetes directory.

**Comment by cpheps** [comment]
> > Removed the additional references. I'm unsure if the kubernetes deployment example still makes sense with that missing.
> 
> It seems to me like it was just a link to that repo for the example config, basically. So we should probably just remove that whole kubernetes directory.

@jsirianni Can you give your input here. I'm happy to remove it but I want to double check on the intent of that doc.

**Review by BinaryFissionGames — APPROVED** [review]

**Pull request merged**
