### PR TITLE
feat(ppc-linux): Add PowerPC architectures for Linux OS Releases

### PR DESCRIPTION
**Pull request by Dylan-M**
### Proposed Change
This PR will introduce PowerPC (ppc64 and ppc64le) Linux build and release artifacts. These have been tested on an Enterprise Linux ppc64le system.

Access for testing can be provided. The test system is running on SiteOx, and we rented it only for a month.

##### Checklist
- [X] Changes are tested
- [x] CI has passed

### CODE REVIEW

**Review by cpheps — COMMENTED** [review]
This does build. Are we expecting PowerPC builds to work with BPOP and does upgrading them work? I see we're creating a PowerPC updater too.

**Comment by Dylan-M** [comment]
> This does build. Are we expecting PowerPC builds to work with BPOP and does upgrading them work? I see we're creating a PowerPC updater too.

That is correct. The updater should work, since it is all just using the existing Linux code and services.

**Comment by Dylan-M** [comment]
> Looks good. We'll need to do some stuff on the BPOP side to support upgrades, but I think this should otherwise just work for the initial install.

Cool. Is there a specific branch I should be targeting? This branch being in merge freeze.

**Comment by BinaryFissionGames** [comment]
> Cool. Is there a specific branch I should be targeting? This branch being in merge freeze.

You can point this to the `release/v1.44.0` branch, I've just created it. That branch will be rebased onto main after we release, so if you run into trouble rebasing after release of v1.43.0, let me know.

**Review by cpheps — APPROVED** [review]

**Pull request merged**
